#standardSQL
CREATE TABLE
  gameprompt_metrics.lotr_metrics ( gameprompt_info STRING NOT NULL,
    datetime TIMESTAMP NOT NULL,
    character_key STRING NOT NULL,
    character_version STRING NOT NULL,
    question_id STRING NOT NULL,
    pod_uid STRING,
    cpu_info STRING,
    startup_time FLOAT64,
    question_text STRING NOT NULL,
    answer_text STRING NOT NULL,
    prompt_time FLOAT64 NOT NULL,
    deadlock_time FLOAT64 NOT NULL,
    model_name STRING NOT NULL,
    llama_threads INT64,
    llama_seed INT64,
    llama_context_size INT64,
    llama_repeat_penalty FLOAT64,
    llama_gpu_layers INT64,
    model_temperature FLOAT64 NOT NULL,
    model_max_output_tokens INT64 NOT NULL,
    vertexai_top_k INT64,
    vertexai_top_p FLOAT64,
    ) OPTIONS ( description="LOTR GamePrompt Server Metrics")