// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: api/gameprompt.proto

package gameprompt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AreYouBusyQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
}

func (x *AreYouBusyQuestion) Reset() {
	*x = AreYouBusyQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gameprompt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreYouBusyQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreYouBusyQuestion) ProtoMessage() {}

func (x *AreYouBusyQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameprompt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreYouBusyQuestion.ProtoReflect.Descriptor instead.
func (*AreYouBusyQuestion) Descriptor() ([]byte, []int) {
	return file_api_gameprompt_proto_rawDescGZIP(), []int{0}
}

func (x *AreYouBusyQuestion) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type AreYouBusyAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busy bool `protobuf:"varint,1,opt,name=busy,proto3" json:"busy,omitempty"`
}

func (x *AreYouBusyAnswer) Reset() {
	*x = AreYouBusyAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gameprompt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreYouBusyAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreYouBusyAnswer) ProtoMessage() {}

func (x *AreYouBusyAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameprompt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreYouBusyAnswer.ProtoReflect.Descriptor instead.
func (*AreYouBusyAnswer) Descriptor() ([]byte, []int) {
	return file_api_gameprompt_proto_rawDescGZIP(), []int{1}
}

func (x *AreYouBusyAnswer) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId    string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Character string `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	Question  string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gameprompt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameprompt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_gameprompt_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *Question) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gameprompt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameprompt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_api_gameprompt_proto_rawDescGZIP(), []int{3}
}

func (x *Answer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_api_gameprompt_proto protoreflect.FileDescriptor

var file_api_gameprompt_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x22, 0x2d, 0x0a, 0x12, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x42, 0x75, 0x73, 0x79,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49,
	0x64, 0x22, 0x26, 0x0a, 0x10, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x42, 0x75, 0x73, 0x79, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x75, 0x73, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x75, 0x73, 0x79, 0x22, 0x5d, 0x0a, 0x08, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x95, 0x01, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0a, 0x41, 0x72, 0x65, 0x59, 0x6f,
	0x75, 0x42, 0x75, 0x73, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2e, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x42, 0x75, 0x73, 0x79, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2e, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x42, 0x75, 0x73, 0x79, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x41, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x73, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gameprompt_proto_rawDescOnce sync.Once
	file_api_gameprompt_proto_rawDescData = file_api_gameprompt_proto_rawDesc
)

func file_api_gameprompt_proto_rawDescGZIP() []byte {
	file_api_gameprompt_proto_rawDescOnce.Do(func() {
		file_api_gameprompt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gameprompt_proto_rawDescData)
	})
	return file_api_gameprompt_proto_rawDescData
}

var file_api_gameprompt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_gameprompt_proto_goTypes = []interface{}{
	(*AreYouBusyQuestion)(nil), // 0: gameprompt.AreYouBusyQuestion
	(*AreYouBusyAnswer)(nil),   // 1: gameprompt.AreYouBusyAnswer
	(*Question)(nil),           // 2: gameprompt.Question
	(*Answer)(nil),             // 3: gameprompt.Answer
}
var file_api_gameprompt_proto_depIdxs = []int32{
	0, // 0: gameprompt.Converse.AreYouBusy:input_type -> gameprompt.AreYouBusyQuestion
	2, // 1: gameprompt.Converse.AskQuestion:input_type -> gameprompt.Question
	1, // 2: gameprompt.Converse.AreYouBusy:output_type -> gameprompt.AreYouBusyAnswer
	3, // 3: gameprompt.Converse.AskQuestion:output_type -> gameprompt.Answer
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gameprompt_proto_init() }
func file_api_gameprompt_proto_init() {
	if File_api_gameprompt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gameprompt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreYouBusyQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gameprompt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreYouBusyAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gameprompt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gameprompt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gameprompt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gameprompt_proto_goTypes,
		DependencyIndexes: file_api_gameprompt_proto_depIdxs,
		MessageInfos:      file_api_gameprompt_proto_msgTypes,
	}.Build()
	File_api_gameprompt_proto = out.File
	file_api_gameprompt_proto_rawDesc = nil
	file_api_gameprompt_proto_goTypes = nil
	file_api_gameprompt_proto_depIdxs = nil
}
